all:
	g++ -Wall -o counting_sort counting_sort.cpp
	g++ -Wall -o bucket_sort bucket_sort.cpp
	g++ -Wall -o radix radix.cpp

counting_sort:
	g++ -Wall -o counting_sort countring_sort.cpp

bucket_sort:
	g++ -Wall -o bucket_sort bucket_sort.cpp

radix_sort:
	g++ -Wall -o radix radix.cpp

clear:
	rm counting_sort
	rm bucket_sort
	rm radix

