all:
	g++ -Wall -o problem21 p2.1.cpp
	g++ -Wall -o problem22 p2.2.cpp
	g++ -Wall -o problem23 testWindGauge.cpp WindGauge.cpp
	g++ -Wall -o problem24 p2.4.cpp
	g++ -Wall -o problem25 p2.5.cpp
	g++ -Wall -o problem26 testAccessSet.cpp Access.cpp
	g++ -Wall -o problem27 p2.7.cpp

p1:
	g++ -Wall -o problem21 p2.1.cpp

p2:
	g++ -Wall -o problem22 p2.2.cpp

p3:
	g++ -Wall -o problem23 testWindGauge.cpp WindGauge.cpp

p4:
	g++ -Wall -o problem24 p2.4.cpp

p5:
	g++ -Wall -o problem25 p2.5.cpp

p6:
	g++ -Wall -o problem26 testAccessSet.cpp Access.cpp

p7:
	g++ -Wall -o problem27 p2.7.cpp

clear:
	rm problem2*
