all:
	g++ -Wall -o bubblesort bubblesort.cpp
	g++ -Wall -o heapsort heapsort.cpp
	g++ -Wall -o heapsortvar heapsortvar.cpp

bubblesort:
	g++ -Wall -o bubblesort bubblesort.cpp

heapsort:
	g++ -Wall -o heapsort heapsort.cpp

heapsrotvar:
	g++ -Wall -o heapsortvar heapsortvar.cpp

clear:
	rm bubblesort
	rm heapsort
	rm heapsortvar
